// ESLint flat config for the readable JS sources under ``assets/src/js``.
//
// The Python side of this repo is gated by ruff, mypy and a 95% coverage
// floor; the ~650 lines of hand-written JS that ship inline in every
// rendered page had no static analysis at all. These scripts are
// CSP-hash-pinned and run on a public page, so a reference error or an
// accidental global is a production bug with no test behind it.
//
// Scope and style notes:
//
//   * Only ``assets/src/js`` is linted. ``assets/*.js`` is generated by
//     ``scripts/build_assets.py`` (rjsmin) and is byte-compared in CI --
//     linting the minified output would report on machine-written code.
//   * ``sourceType: script`` -- these are plain inline ``<script>``
//     payloads, not modules. The idiom is ES5-flavoured (``var``,
//     ``function``, IIFE) to keep the inline bytes small, but the
//     sources are not literally ES5: ``scroll_hint.js`` uses trailing
//     commas in calls (ES2017), which is what the first eslint run
//     caught. ``ecmaVersion: 2020`` matches what the page already
//     requires of a browser elsewhere (``@container`` queries,
//     ``ResizeObserver``, ``backdrop-filter``).
//   * Correctness rules only, no stylistic ones. Three of the sources
//     (``hash_clear.js`` and the leading IIFE of ``nav_scroll.js`` /
//     ``trades_sort.js``) are checked in pre-minified, so any
//     whitespace or line-length rule would fire on them without saying
//     anything about the code.

export default [
  {
    files: ["assets/src/js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "script",
      globals: {
        // Browser surface the scripts actually touch. Declared
        // explicitly rather than pulled from a ``globals`` package so
        // the hook needs no extra dependency, and so an unexpected
        // global (a typo'd ``documnet``, a stray ``$``) is reported
        // rather than silently allowed.
        window: "readonly",
        document: "readonly",
        location: "readonly",
        addEventListener: "readonly",
        removeEventListener: "readonly",
        history: "readonly",
        matchMedia: "readonly",
        getComputedStyle: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        Math: "readonly",
        JSON: "readonly",
        Date: "readonly",
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: true,
    },
    rules: {
      // The bugs that actually bite in inline browser scripts.
      "no-undef": "error",
      // ``caughtErrors: "none"``: the sources predate optional catch
      // bindings, so every ``try {} catch (e) {}`` guard has to name a
      // binding it never reads. Flagging those would be flagging the
      // language, not the code.
      "no-unused-vars": ["error", { args: "none", caughtErrors: "none" }],
      "no-redeclare": "error",
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "error",
      "no-cond-assign": "error",
      "no-constant-condition": "error",
      "no-self-compare": "error",
      "no-sparse-arrays": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "no-implicit-globals": "error",
      "no-eval": "error",
      "no-implied-eval": "error",
      eqeqeq: ["error", "smart"],
    },
  },
];
